[package]
name = "quic-geyser-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = { workspace = "true" }
solana-streamer = { workspace = "true" }
serde = { workspace = "true" }
bincode = { workspace = "true" }
lz4 = { workspace = "true" }
quinn = { workspace = "true" }
rustls = { workspace = "true", default-features = false }
pem = { workspace = "true" }
anyhow = { workspace = "true" }
tokio = { workspace = "true" }

[dev-dependencies]