[package]
name = "quic-geyser-common"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = "true" }
solana-streamer = { workspace = "true" }
solana-net-utils = { workspace = "true" }
serde = { workspace = "true" }
bincode = { workspace = "true" }
lz4 = { workspace = "true" }
quinn = { workspace = "true" }
rustls = { workspace = "true", default-features = false }
pem = { workspace = "true" }
anyhow = { workspace = "true" }
tokio = { workspace = "true" }
log = { workspace = "true" }

[dev-dependencies]